[package]
name = "parquet2arrow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "9.1.0"
parquet = "9.1.0"
clap = { version = "3.1.5", features = ["derive"] }
anyhow = "1.0.55"
